INSERT INTO ROOM (NAME, ROOM_NUMBER, BED_INFO) VALUES ('ROOM1', 'P1', '1Q')
INSERT INTO ROOM (NAME, ROOM_NUMBER, BED_INFO) VALUES ('ROOM2', 'P2', '1Q')
INSERT INTO ROOM (NAME, ROOM_NUMBER, BED_INFO) VALUES ('ROOM3', 'P3', '1Q')
INSERT INTO ROOM (NAME, ROOM_NUMBER, BED_INFO) VALUES ('ROOM4', 'P4', '1Q')
INSERT INTO ROOM (NAME, ROOM_NUMBER, BED_INFO) VALUES ('ROOM5', 'P5', '1Q')


INSERT INTO GUEST (LAST_NAME, FIRST_NAME, PHONE_NUMBER) VALUE ('MARCA', 'DOMINICA', '70828373623')
INSERT INTO GUEST (LAST_NAME, FIRST_NAME, PHONE_NUMBER) VALUE ('DIAZ', 'MARIA', '8392733238')
INSERT INTO GUEST (LAST_NAME, FIRST_NAME, PHONE_NUMBER) VALUE ('MARC', 'ZOLEY', '38723373623')

INSERT INTO RESERVATION (ROOM_ID, GUEST_ID, RES_DATES) VALUES ((SELECT ROOM_ID FROM ROOM WHERE ROOM_NUMBER = 'P2'),
(SELECT GUEST_ID FROM GUEST WHERE LAST_NAME = 'DIAZ'), '2020,01,01')
INSERT INTO RESERVATION (ROOM_ID, GUEST_ID, RES_DATES) VALUES ((SELECT ROOM_ID FROM ROOM WHERE ROOM_NUMBER = 'P4'),
(SELECT GUEST_ID FROM GUEST WHERE LAST_NAME = 'MARCA'), '2020,06,01')
INSERT INTO RESERVATION (ROOM_ID, GUEST_ID, RES_DATES) VALUES ((SELECT ROOM_ID FROM ROOM WHERE ROOM_NUMBER = 'P3'),
(SELECT GUEST_ID FROM GUEST WHERE LAST_NAME = 'MARC'), '2020,02,01')