CREATE TABLE ROOM(
ROOM_ID BEGINT AUTO_INCREMENT PRIMARY KEY,
NAME VARCHAR(16) NOT NULL,
ROOM_NUMBER CHAR(2) NOT NULL UNIQUE,
BED_INFO CHAR(2) NOT NULL
);

CREATE TABLE GUEST(
GUEST_ID BEGINT AUTO_INCREMENT PRIMARY KEY,
FIRT_NAME VARCHAR(64),
LAST_NAME VARCHAR(64),
PHONE_NUMBER VARCHAR(24)

);

CREATE TABLE RESERVATION(
RESERVATION_ID BEGINT AUTO_INCREMENT PRIMARY KEY,
ROOM_ID BEGINT NOT NULL,
GUEST_ID BEGINT NOT N24,
RES_DATE DATE
);

ALTER TABLE RESERVATION ADD FOREIGN KEY (ROOM_ID) REFERENCES ROOM(ROOM_ID);
ALTER TABLE RESERVATION ADD FOREIGN KEY (GUEST_ID) REFERENCES ROOM(GUEST_ID);
CREATE INDEX IDX_RES_DATE_ON ON RESERVATION(RES_DATE)